name: deepseek_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  openai_dart: ^0.4.5
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.6.1
  flutter_markdown: ^0.7.6+1
  flutter_markdown_latex: ^0.3.4
  markdown: ^7.3.0
  gpt_markdown: ^1.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.5
  package_info_plus: ^8.2.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.2
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true